# -*- coding: utf-8 -*-
from requests import Session

import pywttr


def test_validation() -> None:
    location = "New York"
    pywttr.en.get_forecast(location)
    with Session() as session:
        pywttr.af.get_forecast(location, session=session)
        pywttr.am.get_forecast(location, session=session)
        pywttr.ar.get_forecast(location, session=session)
        pywttr.az.get_forecast(location, session=session)
        pywttr.be.get_forecast(location, session=session)
        pywttr.bg.get_forecast(location, session=session)
        pywttr.bn.get_forecast(location, session=session)
        pywttr.bs.get_forecast(location, session=session)
        pywttr.ca.get_forecast(location, session=session)
        pywttr.cs.get_forecast(location, session=session)
        pywttr.cy.get_forecast(location, session=session)
        pywttr.da.get_forecast(location, session=session)
        pywttr.de.get_forecast(location, session=session)
        pywttr.el.get_forecast(location, session=session)
        pywttr.eo.get_forecast(location, session=session)
        pywttr.es.get_forecast(location, session=session)
        pywttr.et.get_forecast(location, session=session)
        pywttr.eu.get_forecast(location, session=session)
        pywttr.fa.get_forecast(location, session=session)
        pywttr.fi.get_forecast(location, session=session)
        pywttr.fr.get_forecast(location, session=session)
        pywttr.fy.get_forecast(location, session=session)
        pywttr.ga.get_forecast(location, session=session)
        pywttr.he.get_forecast(location, session=session)
        pywttr.hi.get_forecast(location, session=session)
        pywttr.hr.get_forecast(location, session=session)
        pywttr.hu.get_forecast(location, session=session)
        pywttr.hy.get_forecast(location, session=session)
        pywttr.ia.get_forecast(location, session=session)
        pywttr.id.get_forecast(location, session=session)
        pywttr.is_.get_forecast(location, session=session)
        pywttr.it.get_forecast(location, session=session)
        pywttr.ja.get_forecast(location, session=session)
        pywttr.jv.get_forecast(location, session=session)
        pywttr.kk.get_forecast(location, session=session)
        pywttr.ko.get_forecast(location, session=session)
        pywttr.lt.get_forecast(location, session=session)
        pywttr.lv.get_forecast(location, session=session)
        pywttr.mg.get_forecast(location, session=session)
        pywttr.mk.get_forecast(location, session=session)
        pywttr.mr.get_forecast(location, session=session)
        pywttr.nb.get_forecast(location, session=session)
        pywttr.nl.get_forecast(location, session=session)
        pywttr.nn.get_forecast(location, session=session)
        pywttr.oc.get_forecast(location, session=session)
        pywttr.pl.get_forecast(location, session=session)
        pywttr.pt_br.get_forecast(location, session=session)
        pywttr.pt.get_forecast(location, session=session)
        pywttr.ro.get_forecast(location, session=session)
        pywttr.ru.get_forecast(location, session=session)
        pywttr.sk.get_forecast(location, session=session)
        pywttr.sl.get_forecast(location, session=session)
        pywttr.sr_lat.get_forecast(location, session=session)
        pywttr.sr.get_forecast(location, session=session)
        pywttr.sv.get_forecast(location, session=session)
        pywttr.ta.get_forecast(location, session=session)
        pywttr.te.get_forecast(location, session=session)
        pywttr.th.get_forecast(location, session=session)
        pywttr.tr.get_forecast(location, session=session)
        pywttr.uk.get_forecast(location, session=session)
        pywttr.uz.get_forecast(location, session=session)
        pywttr.vi.get_forecast(location, session=session)
        pywttr.zh_cn.get_forecast(location, session=session)
        pywttr.zh_tw.get_forecast(location, session=session)
        pywttr.zh.get_forecast(location, session=session)
        pywttr.zu.get_forecast(location, session=session)
